# Generated by Django 2.2.4 on 2020-04-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
                ('name', models.CharField(max_length=255)),
                ('want', models.CharField(max_length=500)),
                ('where', models.CharField(max_length=500)),
            ],
        ),
    ]
