# Generated by Django 2.2.4 on 2020-04-27 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='work',
            new_name='Todo',
        ),
    ]
