# Generated by Django 2.2.4 on 2020-05-05 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20200506_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='imgur',
            field=models.TextField(default=12345, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
