# Generated by Django 2.2.4 on 2020-05-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20200507_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='imgur',
            field=models.TextField(max_length=100),
        ),
    ]
